### ISSUE TITLE
Design no figma.

### ISSUE THREAD

**Issue by SayRyan** [Interdisciplinary-Project/Frontend#1]

**Comment by SayRyan** [comment]
Design no figma para dar continuidade no Front-End do site.

**Comment by SayRyan** [comment]
Ainda restam três telas a serem feitas dentro do figma, a página de sobre nós (que está feita naquele design antigo, então poderá dar control+c e control+v), página de políticas de privacidade e termos de uso.

@joao-marcos12 e @DanielFBononi

**Comment by joao-marcos12** [comment]
@DanielFBononi e @joao-marcos12 fizeram os ajustes pedidos por @SayRyan

**Comment by joao-marcos12** [comment]
@DanielFBononi  e @joao-marcos12  fizeram os ajustes pedidos por @SayRyan

**Comment by SayRyan** [comment]
@DanielFBononi e @joao-marcos12 , fechou, guys!!
